schemaVersion: 2.1.0
metadata:
  name: tilt-n-quarkus
attributes:
  .che/che-theia-plugins.yaml: |
    - id: ms-python/python/latest
      override:
        sidecar: {}
    - id: redhat/vscode-yaml/latest
      override:
        sidecar: {}
    - id: redhat/vscode-xml/latest
      override:
        sidecar: {}
    - id: vscode/typescript-language-features/latest
      override:
        sidecar: {}
    - id: bmewburn/vscode-intelephense-client/latest
      override:
        sidecar: {}
  .vscode/extensions.json: |-
    {
      "recommendations": [
        "ms-python/python",
        "redhat/vscode-yaml",
        "redhat/vscode-xml",
        "vscode/typescript-language-features",
        "bmewburn/vscode-intelephense-client"
      ]
    }
  metadata-name-field: generateName
  metadata-name-original-value: ansible-demo
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
- name: tilt-container
  container:
    image: quay.io/devspaces/udi-rhel8@sha256:356f69810dacf3c7f7f0c24c06fc4030c5abc60698985f98155d38d1c6163de5
    env:
      - name: QUARKUS_HTTP_HOST
        value: 0.0.0.0
      - name: MAVEN_OPTS
        value: "-Dmaven.repo.local=/home/user/.m2/repository"
    memoryLimit: 4G
    memoryRequest: 256Mi
    cpuLimit: 1000m
    cpuRequest: 30m
    endpoints:
      - name: quarkus-development-server
        targetPort: 8080
        path: /hello
        protocol: http
        attributes:
          urlRewriteSupported: false
      - name: debug
        targetPort: 5005
        exposure: none
        secure: false
        protocol: tcp
      - name: tests
        targetPort: 8081
        exposure: none
        secure: false
        protocol: tcp
      - name: tilt
        targetPort: 10350
        exposure: public
        protocol: https
        attributes:
          urlRewriteSupported: false
- container:
      args:
        - tail
        - '-f'
        - /dev/null
      image: 'quay.io/nmalvankar/crw-ansible-rh-secure:2.12'
      memoryLimit: 512M
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: venv
          path: /home/jboss/.venv
  name: ansible
commands:
  - id: 0-patchdw
    exec:
      commandLine: 'kubectl patch dw tilt-n-quarkus --type=merge -p ''{"spec": {"template": {"attributes": {"controller.devfile.io/scc": "container-build"}}}}'''
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 0-podmanlogin
    exec:
      commandLine: 'podman login quay.io'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 0-buildah-bud
    exec:
      commandLine: 'buildah bud -t quarkus-sync-image -f src/main/docker/Dockerfile.jvm .'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 1-tilt-up
    exec:
      commandLine: 'tilt up -f Tiltfile.buildah --host 0.0.0.0 --namespace ${DEVWORKSPACE_NAMESPACE}'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 2-poll
    exec:
      commandLine: './poll.sh'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 3-tilt-down
    exec:
      commandLine: 'tilt down -f Tiltfile.buildah'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
