schemaVersion: 2.1.0
metadata:
  name: tilt-n-quarkus
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
- name: tilt-container
  container:
    image: quay.io/mloriedo/universal-developer-image:tilt
    env:
      - name: QUARKUS_HTTP_HOST
        value: 0.0.0.0
      - name: MAVEN_OPTS
        value: "-Dmaven.repo.local=/home/user/.m2/repository"
    memoryLimit: 4G
    memoryRequest: 256Mi
    cpuLimit: 1000m
    cpuRequest: 30m
    endpoints:
      - name: quarkus-development-server
        targetPort: 8080
        path: /hello
        protocol: http
        attributes:
          urlRewriteSupported: false
      - name: debug
        targetPort: 5005
        exposure: none
        secure: false
        protocol: tcp
      - name: tests
        targetPort: 8081
        exposure: none
        secure: false
        protocol: tcp
      - name: tilt
        targetPort: 10350
        exposure: public
        protocol: https
        attributes:
          urlRewriteSupported: false
- name: mariadb
  container:
    image: quay.io/eclipse/che--mariadb:10.7.1-5a8009369ee57c85b6f4a08406147bd9c505cde6b8250d16a27d2a5febfdead7
    memoryLimit: 300Mi
    endpoints:
      - exposure: none
        name: db
        protocol: tcp
        targetPort: 3306
    env:
      - name: MARIADB_USER
        value: petclinic
      - name: MARIADB_PASSWORD
        value: petclinic
      - name: MARIADB_DATABASE
        value: petclinic
      - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
        value: allow
      - name: PS1
        value: $(echo ${0}) $
    volumeMounts:
      - name: mysqldata
        path: /var/lib/mysql

- name: mysqldata
  volume:
    size: 256Mi

commands:
  - id: 0-patchdw
    exec:
      commandLine: 'kubectl patch dw tilt-n-quarkus --type=merge -p ''{"spec": {"template": {"attributes": {"controller.devfile.io/scc": "container-build"}}}}'''
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 0-podmanlogin
    exec:
      commandLine: 'podman login quay.io'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 0-buildah-bud
    exec:
      commandLine: 'buildah bud -t quarkus-sync-image -f src/main/docker/Dockerfile.jvm .'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 1-tilt-up
    exec:
      commandLine: 'tilt up -f Tiltfile.buildah --host 0.0.0.0 --namespace ${DEVWORKSPACE_NAMESPACE}'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 2-poll
    exec:
      commandLine: './poll.sh'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
  - id: 3-tilt-down
    exec:
      commandLine: 'tilt down -f Tiltfile.buildah'
      workingDir: ${PROJECT_SOURCE}/201-quarkus-live-update
      component: tilt-container
