kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: m2-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-sync-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-sync-demo
  template:
    metadata:
      labels:
        app: quarkus-sync-demo
    spec:
      volumes:
        - name: m2-cache
          persistentVolumeClaim:
            claimName: m2-cache
      containers:
        - name: quarkus-sync-demo
          env:
            - name: MAVEN_OPTS
              value: '-Dmaven.repo.local=/project/.m2/repository'
          ports:
            - name: http-web
              containerPort: 8080
              protocol: TCP
            - name: jdwp-debug
              containerPort: 5005
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: m2-cache
              mountPath: /project
          image: 'quay.io/mmascia/quarkus-sync-image'
